### ISSUE TITLE
Virus scan of binary attachment

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-storage#104]
## Description
It is possible for orgs and users to attache binary files to instances of an app. We need to analyze if there is a need to perform virus scan of the binary files.

Likely to be wanted by NBIB as per comment:
![image](https://user-images.githubusercontent.com/36764011/114038444-2b074800-9882-11eb-987f-3063c475cffc.png)

## PO statement:
Binary attachments shall be scanned for virus so that app owners and end users can have the confidence that binary attachments from Altinn have been scanned. This means that all binary attachments added to the app instance shall be checked for virus. After MVP there might be that we shall give the option for app owners to turn off virus scan, as we have already got an indication that app owners do not want us to do so. This however is not in scope for MVP and must be discussed with security team.

## In scope
- Analyze if we need to perform virus scan or we can push that responsibility to the service owner. 
- If needed, analyze what kind of products is available. (Open Source is the assumption)
- Is there any products in public cloud that can do this?

## Acceptance criteria
- When an end user through UI or API is uploading one or more files, the attachment(s) is scanned for virus, if one or more files is identified as a file with virus, the end user should be notified that the file(s) was not uploaded as it was identified as file(s) with virus. It is accepted that all files are declined if only one of several files is infected.
- The implementation should not prevent us from expanding this functionality to only be for certain apps, meaning we might find out that the virus-check is something that the app-owner could decide themselves if they would like Altinn to perform or not.

## Consideration
- Look at complete solutions that also
  - secure container building and deployments - for instance, https://anchore.com/ .
  - provide runtime detection
  - cost - how is the solution priced/scaled
  - easy to deploy and maintain
  - integrates with Sentinel/SIEM
      
- Possible products  
  - https://www.attachmentscanner.com/ 
  - https://peterrombouts.nl/2019/04/15/scanning-blob-storage-for-viruses-with-azure-functions-and-docker/
  - https://www.clamav.net/  
  - http://jasonhaley.com/post/Virus-Scan-File-Uploads-Using-Multi-Container-Web-App
  - [Symantec Cloud Workload Protection for Storage](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/symanteccorporation.symccwps-app) 
 
- Discarded
  - https://developers.virustotal.com/ - Not for commercial use.

- Other products
  - https://azure.microsoft.com/en-us/blog/advanced-threat-protection-for-azure-storage-now-in-public-preview/
  - https://www.trendmicro.com/azure/
  - https://www.sophos.com/en-us/solutions/public-cloud/azure.aspx

## Analysis
[Internal link to analysis document](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/142344240/Virusskanning+av+bin+re+vedlegg)

## Tasks
- [x] Analyze if we need to perform virus scan - Yes, it is needed
- [ ] Decide possible product
- [ ] Define archticture
- [ ] Create POC task
- [ ] Create build task

**Comment by tba76** [comment]
Virus scan er nå tilgjengelig i produksjon :)

https://github.com/Altinn/altinn-file-scan
