### ISSUE TITLE
Trigger an alert if Storage is getting errors for requests to storage accounts.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#108]
### Description

Implement an alert to trigger when the Storage application is receiving non-successful status codes in its requests to any storage account or cosmos db. Requests against storage accounts or PostgreSQL should ideally never fail. 

If we see many intermittent/temporary/self resolving errors leading to alerts we can consider changing the parameters for the alert.

### Additional Information

This issue were created when we ran into issues with communication with a storage account for a specific application owner. Usually relateed to invalid SAS tokens and unable to generate a new valid one.

### Tasks

- [ ] Create a query that is trying to find failed requests from Storage to the underlying storage services.
- [ ] Create an alert based on the query.
- [ ] Have the alert published to the appropriate slack channels.

### Acceptance Criterias

- [ ] One or more failed requests against underlying storage services triggers an alert.

**Comment by olebhansen** [comment]
Issue with SAS tokens no longer relevant after introduction of Workload Identity. Monitoring already in place. Asses if change is improving or need (other specialized handling).
