### ISSUE TITLE
Prevent download of blob marked as infected

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#160]
### Description

Infected files can currently be downloaded normally. We should consider stopping downloads if FileScan has marked a file as infected.

### Tasks

- [ ] Add a file scan status check to the download logic. 
- [ ] Identify an appropriate 4xx status code. Ideas:
    - [ ] 404 to indicate deleted?
    - [ ] 424 Failed Dependency? (means that the request failed due to the failure of a previous request.)
    - [ ] 423 Locked
    - [ ] 410 Gone

### Acceptance Criterias

- [ ] A GET request on a DataElement marked as infected results in status code: **

**Comment by olebhansen** [comment]
See also filescan #156 + #49. Fundamental question is what do do about filescanning and if we should permitt infected files. Clarify how the current solution works and if it is needed to go above and beyond this (and if so "how").
