### ISSUE TITLE
Analyse cause of uneven load towards Storage

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#17]
## Description
Load testing w14 2022 revealed uneven load towards the nodes running the storage component. 
Should analyse the cause of this, and recomment further steps to mitigate this behavior. 
![image](https://user-images.githubusercontent.com/47737608/161754404-6693aa8b-4c75-4b8a-82ca-4ede9ec99f98.png)

## In scope
- [ ] Identify if this was due to upscaling the node count or not isolated

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by SandGrainOne** [comment]
We don't consider the uneven load to be an issue at this point in time. It's not an issue we see during normal operations.

There is no clear idea for how to analyse this and we are not sure what we would do with the result.
