### ISSUE TITLE
Upgrade Storage to .NET 7

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#189]
### Description

Upgrade Storage components to .NET 7. 
Leave functions at current version

### Tasks

- [x] Make updates
- [x] QA
- [x] Manual test

### Acceptance Criterias
- [x] Test and storage project run .NET 7
- [x] Storage.Interface supports .netstandard 2.0
- [x] Function projects run .NET 6
