### ISSUE TITLE
Change Storage to use PostgreSQL instead of CosmosDB

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#193]
### Description

Change Storage to use PostgreSQL instead of CosmosDB

#### About possible downtime
We can have downtime in storage related to this change, but the duration should be limited and user's must be notified minimum 5 days ahead of time. 

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-storage/issues/191
- [ ] https://github.com/Altinn/altinn-storage/issues/192
- [ ] https://github.com/Altinn/altinn-storage/issues/205
- [ ] Create new temporary pipline for branch deploy to AT23
- [ ] Regression testing
- [ ] Perform data migration where old data is copied from CosmosDB to PostgreSQL
```
