### ISSUE TITLE
Create signing document

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/altinn-storage#207]
### Description

As part of a user performing a signing action we should log a specific signature document capturing the action as well as linking it to the data it is signing of on. The signature document should be captured for both a positive signature and a negative signature ie. the signee refused to sign.

### Additional Information

Related epic: https://github.com/Altinn/app-template-dotnet/issues/170

### Tasks

- [x] #211
- [x] #210
- [x] #208
- [x] #212
- [x] #209
- [x] #213
- [x] #221

### Acceptance Criterias

- [x] Capture a positive signature
- [x] Capture a negative signature
- [x] Signature documents is captured and stored as a specific datatype
