### ISSUE TITLE
Define and create a model for the Sign Request.

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-storage#208]
### Description

Update storage interface to expose new model for Sign Request

### Tasks

- [x] Agree on new request model and property names
- [x] Update storage interface
- [ ] QA

### Acceptance Criterias

- [ ] New sign request model exists
