### ISSUE TITLE
Define and create a model to represent the signature document (different from the sign request model)

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-storage#209]
### Description

Update storage interface to expose new properties for data element and dataTypes

### Additional Information

Blocked by #208

### Tasks

- [x] Agree on new signature model name and property names
- [x] Update storage interface
- [x] QA
- [x] Push new puget package 

### Acceptance Criterias

- [x] New signature document model exists
