### ISSUE TITLE
Set up APIM for for new endpoint

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-storage#210]
### Description

New API-endpoint should be defined in APIM. 

### Tasks
- [x] Define endpoint 
- [x] QA
- [x] Test

### Acceptance Criterias

- [x] Deployed to AT21
- [x] Deployed to AT22
- [x] Deployed to AT23
- [x] Deployed to AT24
- [x] Deployed to Yt01
- [x] Deployed to tt02
- [ ] Deployed to prod
