### ISSUE TITLE
Implement API endpoint that can take a signing request in a new controller

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-storage#211]
### Description

Create new controller and endpoint in storage. New InstanceService that creates the signing document.
PlatformAccessToken is requred.

### Additional Information

HTTP verb: POST
Route: /storage/api/v1/instances/{instanceOwnerParyId}/{instanceGuid}/sign

### Tasks

- [x] Create controller and endpoint, input will be defined in #208 
- [x] Create a new InstanceService class to hold business logic. Use DataService implemented in #212
- [x] Implement authorization 
  - UserId and PartyId must be part of claims

### Acceptance Criterias
- [x] User is authorized
- [x] Returns 201 Created when signing document is created sucsessfully
- [x] Requests where userId and/or partyId is missing should be rejected with 400 response
- [x] Signed Instance event is registered if signature is stored successfully
- [x] Signed Instance event is not registered if signature is not stored successfully
