### ISSUE TITLE
Implement logic to create a hash of a data element. Expand DataService. Should handle a single data element.

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-storage#212]
### Description

Create new method in DataService to create hash of data element. 

### Tasks

- [x] Create new method in DataService, data element guid as input
- [x] Get file from blob-storage
- [x] Create and return Sha-256 hash

### Acceptance Criterias
- [x] New method returns Sha-256 hash
