### ISSUE TITLE
Support references on data elements

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#223]
### Description

Related to: altinn/app-lib-dotnet#137
The application needs a way to know which data elements are generated as a result of a particular dataElement to be able to unlock/delete them if process is rolled back.

### Tasks
- [x] Update storage interface
- [x] Update controller endpoints in storage to accept reference info
- [x] QA
- [x] Duplicate logic in localtest
- [x] Manual test
- [x] Automated tests

### Acceptance Criterias
- [x] DataElement references are persisted on the dataElement object
- [x]  Value, ValueType and ReferenceType are set for each reference generated
