### ISSUE TITLE
Plan testing, find test users and write down what we want tested

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#293]
## Description

|Updated for testing of PRODUCTION!|
|----|

Make a plan for the testing of Storage.

## Tasks
- [x] Write test scripts
    - [x] Message box, archive, recycle bin, search, receipt
    - [x] App use
    - [x] altinn.studio testing (deploy)
    - [x] Cleanup
- [x] Find test data
- [x] Perform some pre migration testing
- [x] Build apps that can be used in testing
    - [x] [FileScan end to end](https://ttd.apps.altinn.no/ttd/filescan-end-to-end/)
    - [x] [Apps test prod](https://ttd.apps.altinn.no/ttd/apps-test-prod/)

### Message box
1. Sign in as a person
2. Select a reportee to open the "Inbox"
3. Verify state by comparing state from before switch. There are some pre deploy notes in a separate [issue](#292). (Some testers have separate notes.)
    1. Verify the state of the inbox with the pre deploy notes
    2. Verify the state of the archive with the pre deploy notes
    3. Verify the state of the recycle bin with the pre deploy notes
    4. Verify the result of advanced search with the pre deploy notes

### App testing
1. Sign in as a person
2. Select a reportee to open the "Inbox"
3. Start an app, fill out the form and submit.
    - [FileScan end to end](https://ttd.apps.altinn.no/ttd/filescan-end-to-end/)
    - [Apps test prod](https://ttd.apps.altinn.no/ttd/apps-test-prod/)
4. Ensure that the end result is as expected. (Auto delete settings etc.)

### Altinn studio testing
1. Test deploy of an app.
2. Test redeploy of an app.

### Clean up verification
1. Prepare a set of queries to search the CosmosDB collections for resources that would be deleted by the existing clean up functions. 
2. Run the queries right after having stopped changes in CosmosDB.
3. Trigger the clean up for PostgreSQL and compare the results.

## Test apps
A list of possible test apps.
1. [FileScan end to end](https://ttd.apps.altinn.no/ttd/filescan-end-to-end/)
    App used by the use case testing of file scan in production
2. [Apps test prod](https://ttd.apps.altinn.no/ttd/apps-test-prod/)
    App used by the primary use case tests

## Test data

<details>
<summary>Test data from Tenor. Not usable in production.</summary>
<br>
These are not specifically for testing of Storage, but might be of help.

### 07837399275 GILD TIGER

User can prepresent the following organisations:
313441571 LIKEGYLDIG VELKOMMEN APE
- Styremedlem
    - Energi, miljø og klima
    - Regnskapsmedarbeider
    - Utfyller/Innsender

### 04884299727 OVERGANG MODERAT

User can prepresent the following organisations:
312508729 LYS ENTUSIASTISK APE
- Styremedlem
    - Energi, miljø og klima
    - Regnskapsmedarbeider
    - Utfyller/Innsender

### 18874198354 PRIKKETE LEKEPLASS

User can represent the following organisations:
312508729 LYS ENTUSIASTISK APE
- Daglig leder
- Styrets leder
    - Energi, miljø og klima
    - Regnskapsmedarbeider
    - Utfyller/Innsender
    - +++

313731596 RETORISK IMPULSIV ISBJØRN SA
- Forretningsfører
- Styremedlem
    - Energi, miljø og klima
    - Regnskapsmedarbeider
    - Utfyller/Innsender
    - Tilgangsstyring
    - Plan- og byggesak
    - Begreenset signeringsrettighet
    - Kommunale tjenester
    - Lønn og personalmedarbeider
</details>
