### ISSUE TITLE
Remove Cosmos code from the storage component

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#308]
### Description
Remove dead/unused code related to Cosmos DB. Clean up in dependencies.

### Tasks
- [x] Remove feature flag `GeneralSettings.UsePostgreSQL` while leaving any code for when the feature is on/true.
- [x] Remove unused code.
- [x] Remove functions
- [x] Disable Azure DevOps analysis, build and release pipelines related to Storage Azure Functions
~~- [ ] Localtest~~ No dependencies to cosmos, so no changes required
~~- [ ] Infrastructure: Remove~~ https://github.com/Altinn/altinn-platform/issues/660

**Comment by acn-sbuad** [comment]
https://github.com/Altinn/altinn-platform/issues/660 infra tasks extracted to seperate issue
