### ISSUE TITLE
Update storage to Dotnet 8 and patch dependencies with new major versions

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#309]
### Description

Upgrade Web API and test projects to .NET 8

### Tasks
- [x] Upgrade project and dependencies
- [x] Upgrade references in dockerfile
- [x] QA
- [x] Test

### Acceptance Criterias
- [x] Regression tests are successful
- [x] Storage runs .NET 8
