### ISSUE TITLE
Add CName for production database to DNS 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#310]
### Description

CName for the storage db in production is not registered in DNS and should be so. 

### Additional Information

For Storage in production the connection string now holds the actual hostname of the server instead of the CNAME.

### Tasks

- [x] Add to DNS
- [x] Update connection string to use cname in values.yaml
- [ ] Verification

### Acceptance Criterias

- [ ] Database is referred to by CNAME

**Comment by SandGrainOne** [comment]
@ootneim Is this a quick fix? Maybe already done?

**Comment by ootneim** [comment]
It's not done yet. Unknown how much job to get it implemented. 
Something we can look into after testing backup of Apps Storage account.

**Comment by ootneim** [comment]
We have a simular issue in the Backup DR Epic
https://github.com/Altinn/altinn-platform/issues/458

**Comment by ootneim** [comment]
Looks like the CNAME is incorrect in DNS.

storage-postgres.altinn.no -> altinn-storage-db-pgflex.postgres.database.azure.com

Correct setting is:
storage-postgres.altinn.no -> altinn-storage-db-prod-pgflex.postgres.database.azure.com

@bengtfredh or @Herskis have access to update the DNS record.

**Comment by bengtfredh** [comment]
@ootneim CNAME is updated - record has TTL 2h - but can take up to 24 hour for all dns to be updated
