### ISSUE TITLE
Identify and configure necessary accesses for Storage

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#363]
### Description
Storage needs access to Azure resources with workload identity:

- [ ] Platform KeyVault
- [ ] Application Insights
- [ ] Application owner Storage accounts
- [ ] PostgreSQL server database schema
- [ ] Other?

### Tasks
- [ ] Configure the necessary accesses through workload identity
- [ ] Update the code to no longer use the kvSettings to access the KeyVault
- [ ] Implement a good alternative for when Receipt is running in local dev. 
- [ ] QA
- [ ] Manual tests

### Acceptance criteria
- [ ] Storage can access the platform key vault without the explicitly shared credentials.

**Comment by SandGrainOne** [comment]
Duplicate of #411
