### ISSUE TITLE
Upgrade storage-end-to-end app to version 4/8 of the template

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#366]
### Description

We should consider updating the `storage-end-to-end` to the latest versions of the app template. Apps can now be on dotnet 8 with version 8 of the backend and use the latest front-end changes by using version 4 of the frontend.

### Additional Information

We need to perform the same with the `filescan-end-to-end` app as well. 

### Tasks
- [x] Run the upgrade tool to get most changes automatically added
- [x] Build and test the changes
- [x] Update the docker file if not already done by the tool

### Acceptance Criteria

- [x] The new version of `storage-end-to-end` works without functional changes
