### ISSUE TITLE
Set up a system for automatically running load tests after deploy to YT

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#371]
## Description
We want to track the performance of our solution and be able to quickly identify if changes to our code or new features introduce a degradation of the performance of platform. 

One way to do this is to have bench mark load tests that can be run with each change / deploy to YT. 

## Consideration
Test results from a single test gives us little insights. We will need somewhere to persist and present the test results to easily identify if and when a change to the performance occurs.

Should the number of replicas match what we are running in production at the time or be scaled up to a maximum? And regardless of what we go for here, what is the best way to scale the environment up and down with minimal effort? 

## Tasks
- [ ] Identify relevant tests for the platform components tests suites
- [ ] Set up a pipeline (DevOps or GitHub) to trigger relevant tests
- [ ] Set up dashboard to present test results 

~~- Automatisk kjøring av RF-0002 testene etter deploy til YT01~~
~~- Skalere automatisk opp før kjøring og ned etter kjøring.~~

## Acceptance criteria
- [ ] Issues are created describing what tests are missing for the test suite to be complete
- [ ] There is a dashboard available to the team where the performance of the solution over time is available

**Comment by olebhansen** [comment]
Need to be discussed furhter.. we need an actual test first + check if there is planned some common approach.

**Comment by olebhansen** [comment]
Closing - this is evolving based on capabilities and team needs. It is a good thing, but the issue is too generic/wishfull.
