### ISSUE TITLE
Create a GitHub App for assigning issues to projects

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#372]
### Description

Currently we are using a workflow to auto assign issues to projects, by creating an app that completes this task we will be able use more granulated permissions	

### Additional Information

https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps

### Tasks

- [ ] Implement an app that can create a project item based on a new issue created in a repo 
- [ ] QA
- [ ] Test
- [ ] Register app in relevant repositories

**Permissions**
- Issues: read&write 
- Organization.Projects: read & write

**Subscribe to events**
- issues 

### Acceptance Criterias
- [ ] The app should autoassign new issues to an existing project

**Comment by olebhansen** [comment]
Still relevant @acn-sbuad ? What is the missing feature vs. our current setup?
