### ISSUE TITLE
Find the specific person number for the k6 regression tests for PROD and add it to GitHub secrets in Storage

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#427]
### Description
Find the specific person number for the k6 regression tests for PROD and add it to GitHub secrets in Storage

### Tasks
- [x] Find the specific person number for the k6 regression tests for PROD which is associated with the `REGRESSION_USER_NAME`
- [x] Add it to GitHub secrets in Storage

### Acceptance Criteria
- [x] Regression tests are passing for the Altinn-Storage
