### ISSUE TITLE
Investigate what type of messagebox search requests that are slow

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#44]
### Description

There are a few search requests against the message box API that ends in timeout. We need to investigate what type of requests they are and decide to do to improve the performance.

In this issue we need to retrieve log data from AI and create an overview over parameter use like the number of parties.

### Additional Information
Slow requests last 2 months

```
7/31/2022, 8:42:13.486 PM
7/31/2022, 8:42:02.592 PM
7/31/2022, 8:40:58.575 PM
7/31/2022, 8:40:47.634 PM
7/24/2022, 6:32:31.452 AM
7/9/2022, 5:18:22.215 AM
7/9/2022, 1:33:22.314 AM
6/26/2022, 6:05:04.790 PM
```

### Tasks

- [x] Prepare telemetry to better support performance tests
- [ ] Analyze request bodies for slow requests
- [ ] Set up plan for performance tests

```
requests
| where url contains "sbl/instances" 
| where duration > 1000
| where cloud_RoleName == "platform-storage"
| order by timestamp desc
| project duration, customDimensions
```

### Acceptance Criterias

- [ ] A finished overview over the type of search requests that are too slow.
- [ ] How many single party requests and how many cross party searches during a week.
- [ ] Attempt to identify the type of user-party relationships.
- [ ] Is single party search slow in general or are the aspect with the slow searches? Both

**Comment by acn-sbuad** [comment]
Ice box while we wait for telemetry to be available in production.

**Comment by OddArneSaetervik** [comment]
Denne avventer vi avklaring og/eller tilbakekomst av ytelsesressurs

**Comment by acn-sbuad** [comment]
Closing issue. As we are moving to postgresql performance on old infrastructure is no longer relevant.
