### ISSUE TITLE
Remove the use of Shared Access Signature when accessing application owner storage accounts

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#450]
### Description

Storage has been given a workload identity and contributor access to the application owner storage accounts. This means it should be possible to remove the use of shared access signatures when accessing blobs. We should update logic in BlobRepository to no longer depend on ISasTokenProvider.

### Additional Information

This is a follow up issue to #411 and it's replacing the remaining tasks in linked issue.

### Tasks

- [x] Update the code to no longer acquire a SAS-token when accessing a Application Owner Storage Accounts
- [x] Delete the ISasTokenProvider interface and implementations
- [x] Remove, adjust and create unit tests as needed
- [x] Remove unnecessary values from deployment files
- [x] Review
- [x] Manual tests
- [x] Create an issue for platform to help remove unnecessary terraform definitions

### Acceptance Criteria

- [ ] Storage can access all Application Owner blob storage without the explicitly shared credentials

```[tasklist]
### Blockers
- [ ] https://github.com/Altinn/altinn-storage/issues/514
```

**Comment by SandGrainOne** [comment]
Should we try to update the terraform scripts ourselves?

**Comment by hansdragnes** [comment]
01OCT: consider options/ work around if removing SAS.
