### ISSUE TITLE
Storage: Analyze impact of introducing system users

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-storage#471]
### Description
We will soon start getting requests on our API where there the authenticated caller is a system with a system id instead of a user id. This issue should analyse what type of changes we need to do in our application logic.

The primary concern is authorisazation. A lot of authorization logic is contained in the PEP library published by the Authorization team, but Storage also have logic coded in controllers and services. All of this needs to be checked.

The second concern is whether Storage use the user id for anything else. Two examples of this is our usage of the CreatedBy and LastChangedBy properties in different models. Do we need to do something to be able to separate between systems and users and how would we go about doing it. The two fields are already defined as strings and are used to store the service owner acronym if it's them that are performing operations. We probably need to define new properties to avoid breaking changes. An option would even be to version the API.

The output of this issue should be a new user story with implementation tasks.

### Additional information
The system user feature has been documented here: https://docs.altinn.studio/authentication/guides/systemauthentication-for-apiproviders/

### Tasks
- [x] Analyse the impact of the introduction of systems in custom logic related to authorization
    - [x] Consider both our use of the PEP package as well as custom logic building authorization requests
- [x] Identify places where Storage obtains the user id.
    - [x] Look for usage of ControllerBase.User
    - [x] Look for usage of HttpContext.User
    - [x] Look for usage of bearer token claims.
    - [x] Analyse what we need to do in places where user id is used in metadata.
- [ ] Consider the impact any model changes might have on existing API consumers.
    - [x] Known fields: ChangableElement.CreatedBy, ChangableElement.LastChangedBy
    - [x] Look for other fields.
    - [ ] Analyse what options there are to separate system identifiers from user identifiers in metadata/logs.
- [ ] Is it easy to obtain a name for the system performing operations?
    - [ ] Can we easily replace instances of National Identity Number with a system name?

### Findings
- It's possible to generate a token for a system user using the [token generator](https://github.com/altinn/AltinnTestTools?tab=readme-ov-file#systemuser-tokens-see-docs).
- Establish a systemuser that can be used in testing. Do we need a special app?
- Search for HttpContextAccess results:
    - ClaimsPrincipalProvider has a method GetUser() that returns the ClaimsPrincipal.
        - Used exclusively by AuthorizationService while constructing special authorization requests.  
    - StorageAccessHandler is using the ClaimsPrincipal when creating an Authorization challenge request, but the logic is handled by DecisitionHelper from the PEP package.
    - IdentityTelemetryFilter extracts the UserId claim, but can handle that the value is missing. We would need to add logic for "SystemUserId".
    - InstanceEventsService - tries to find user id to be used in a created instanceevent.
        - The PlatformUser model must be expanded with support for SystemUser
    - OndemandClient and RegisterService is accessing the context, but never the User.
- Search use of User in Controllers
    - DataController - being used to set LastChangedBy and CreatedBy. We will need a new version of the GetUserOrOrgId() method, but also look at the properties being populated.
    - InstancesController - being used to set LastChangedBy and CreatedBy. We will need a new version of the GetUserOrOrgId() method, but also look at the properties being populated.
    - MessageBoxInstancesController - being used to set LastChangedBy. We will need a new version of the GetUserOrOrgId() method, but also look at the properties being populated.
    - ProcessController - being used to set LastChangedBy. We will need a new version of the GetUserOrOrgId() method, but also look at the properties being populated.
    - SignController - being used to set CreatedBy and LastChangedBy on a new data element. We will need a new version of the GetUserOrOrgId() method, but also look at the properties being populated.
- Bearer token is not accessed directly anywhere in Storage.
- UserId use in metadata:
    - The ChangeableElement fields CreatedBy and LastChangedBy should be populated by the organization number of the system user owner. The organization number is available in one of the ClaimsPrincipal claims.
    - The PlatformUser class must be expanded with a field for SystemUserId and a field for SystemUserOrg, (and field for SystemUserName?)
    - ProcessHistoryItem.PerformedBy must be allowed to have a systemuser identifying value. 
    - The model Signee needs to be expanded with fields to accomodate a situation where the active party were a system user. (If this is something we want to support in the signing feature.)

### Breaking changes 
This is an attempt at writing a text we can send to API users.

> [Bakover inkompatible endringer i Apps og Storage APIer]
> 
> I sammenheng med at vi innfører støtte for systembrukere vil det komme endringer i data som eksponeres av Apps og Storage API. Dette er altså i første omgang data endringer og ikke kontraktsendringer. Vi vil likevel informere om dette i tilfelle noen mot formodning skulle gjøre antagelser om innhold i metadata og bruke det til noe. 
> 
> Felter:
> - Instance.CreatedBy
> - Instance.LastChangedBy
> - DataElement.CreatedBy
> - DataElement.LastChangedBy
> 
> Data i disse feltene er allerede en uheldig blanding av verdi-typer. Verdien i disse feltene er i dag enten en UserId eller organisasjonsnummeret til tjenesteeier. Begge disse verdiene er tall og derfor vanskelig å bruke til noe. Det er teknisk mulig å skille på de ved å benytte tallets lengde, men vi håper nå at ingen har gjort noe slikt. 
> 
> Med systembruker innfører vi nå at verdien i disse feltene også vil kunne være organisasjonsnummeret til systembrukerens eier. Alternativet vil være å la feltet stå tomt når operasjon er utført av et system.
> 
> Felter:
> - InstanceEvent.User.UserId
> - InstanceEvent.User.NationalIdentityNumber
> 
> Disse feltene vil i større grad enn før være tomme da vi ikke har noen person identitet når en operasjon er utført av et system. Dette har allerede kunnet forekomme når operasjon er utført av tjenesteeier eller når noen har benyttet en virksomhetsbruker.
> 
> Felter
> - InstanceEvent.User.EndUserSystemId
> 
> Dette feltet er allerede alltid tomt. Altinn 3 har aldri hatt noe støtte for sluttbrukersystemer slik vi kjenner de i Altinn 2.
> 
> Felter:
> - ProcessHistoryItem.PerformedBy
> 
> Dette feltet vil i dag enten inneholde tjenesteeier akronymet eller fødselsnummeret til utførende person. Dette vil vi måtte utvide med en eller annen form for systembrukeridentifiserende verdi. Dette blir høyst sannsynlig organisasjonsnummeret til systemeier.
> 
> Nye felter:
> 
> Med innføring av systembrukerstøtte vil det kunne komme til nye felter i en del av modellene som nevnes her. Formålet med de nye feltene vil være å tilby en bedre representasjon av den som har utført muterende operasjoner på Storage resurser. Dette vil være API kontraktsutvidelser vi mener klienter av disse API'ene skal kunne håndtere. Antagelsen er atlså at eksisterende klienter er i stand til å ignorere felter den ikke kjenner igjen.
> 
> mvh Team Apps & Team Storage
