### ISSUE TITLE
Create APIM definitions for MigrationController

### ISSUE THREAD

**Issue by HenningNormann** [Altinn/altinn-storage#520]
### Description
The endpoints created for the migration project must be available through API Management. Update the OpenAPI spesification for Storage and update API Management with the new definition.

### Tasks
- [ ] Update the OpenAPI spesification
- [ ] Update the Storage APIM policy (if needed)
- [ ] Run the API management update prosedure for Storage. [internal link](https://pedia.altinn.cloud/altinn-3/ops/release-and-deploy/api-management/)

### Acceptance criteria
- [ ] All migration endpoints in the MigrationController is available through API Management.
