### ISSUE TITLE
Test and document get instances parameters

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#540]
### Description
There is at least one undocumented parameter in the get instances endpoint: archiveReference

If the parameter is working/is usable by external parties, the OpenAPI specification should be updated 

https://docs.altinn.studio/api/storage/spec/#/Instances/get_instances

### Tasks
- [x] See if there are more parameters that are undocumented.
- [x] Test the identified parameters
- [x] Update the Open API specification in our docs
- [x] Update the specification published  to API Management 

### Acceptance criteria
- [ ] Documentation mentions archiveReference and how it can be used to find instances based on the archive reference.

**Comment by hggutvik** [comment]
I traced the use of the archiveReference parameter in the get instances query.
It's effect on the query can be observed in the bottom of the following excerpt from [storage.readinstancefromquery_v5](https://github.com/Altinn/altinn-storage/blob/main/src/Storage/Migration/FunctionsAndProcedures/readinstancefromquery.sql#L73), 
```
SELECT i.id, i.instance, i.lastchanged FROM storage.instances i
WHERE 1 = 1
    AND (_continue_idx <= 0 OR
            (_continue_idx > 0 AND _sort_ascending = true  AND (i.lastchanged > _lastChanged_idx OR (i.lastchanged = _lastChanged_idx AND i.id > _continue_idx))) OR
                (_continue_idx > 0 AND _sort_ascending = false AND (i.lastchanged < _lastChanged_idx OR (i.lastchanged = _lastChanged_idx AND i.id < _continue_idx))))
    AND (_appId IS NULL OR i.appid = _appId)
    AND (_archiveReference IS NULL OR i.instance ->> 'Id' like '%' || _archiveReference)
    [...]
```

**Comment by hggutvik** [comment]
[storage.readinstancefromquery_v5](https://github.com/Altinn/altinn-storage/blob/main/src/Storage/Migration/FunctionsAndProcedures/readinstancefromquery.sql) shows how these parameters are used to filter instances

**Comment by hggutvik** [comment]
PR created: https://github.com/Altinn/altinn-studio-docs/pull/1981
