### ISSUE TITLE
Update process state and history (`InstanceEvents`) within a single transaction

### ISSUE THREAD

**Issue by martinothamar** [Altinn/altinn-storage#544]
### Description

During `process/next` in an app, when transitional work has been completed and we are ready to commit the new state and events to Storage, we send

* 1 request for the process state update
* 1 request for each `InstanceEvent` generated

This leads to a race condition for external systems that are polling the Storage API for new instances to pull down. In particular it was noted that when there network issues related to a specific app cluster, the window for the race condition widened to the point that alot of the instances that were polled had updated process state (they were completed) yet not all `InstanceEvent`s were stored. We should have an API for updating both the process state and the `InstanceEvent`s in a single transaction to avoid this issue.

### Additional Information

A workaround for polling systems is to only consume instances that have been completed for some time (importantt to note that this only reduces the probability of errors states)

### Tasks

- [x] Add API to altinn-storage
- [x] Implement API in app-lib, merge and release when new Storage version is deployed 
- [x] Update localtest to match Storage

### Acceptance Criterias

* Apps on the newest version of the backend libriaries use the new endpoint which posts process state update and instance events in a single request, and get back the updated instance
* Storage runs this request in a single transaction
* A new repository is implemented in Storage

**Comment by martinothamar** [comment]
Just discused with @bjorntore, some uncertainty on what we should do about the API contract itself. Ideally we don't want to have Storage authorizing this API request as we have already done so in the app. It is tempting to create a v2 of the API where we do authorization based on Platform Access Token for the APIs that are supposed to always come from the app. If we do Platform Access Token on an adjacent API in v1 things are starting to feel a little inconsistent and messy. What do you think @SandGrainOne ?

**Comment by SandGrainOne** [comment]
We have as one of our tenants to authorize access in every layer. We might discuss exceptions when we implement "system activities", but in this case it's essencially a user action that should involve an authorization check of the user.

**Comment by SimenRokaas** [comment]
Hei, er det noen oppdatering på dette? Dette er fortsatt et ganske kritisk problem for oss (DSB). Vi har vært nødt til å implementere en daglig sjekk på ukvitterte instanser, og må håndtere disse manuelt siden det vanlige mottaket vårt baserer seg på at det finnes et event hos dere.

25/11 meldte SSB og Patentstyret at de også hadde problemer med dette, ref https://altinn.slack.com/archives/C068VDDDR6W/p1732521571002409

**Comment by martinothamar** [comment]
Storage er oppdatert i prod og appen er oppdatert i siste [RC på v8.5](https://github.com/Altinn/app-lib-dotnet/releases/tag/v8.5.0-rc13)
