### ISSUE TITLE
Upgrade Storage to dotnet v9

### ISSUE THREAD

**Issue by hggutvik** [Altinn/altinn-storage#563]
### Description

We should upgrade the Storage application to .net9. .net9 has standard time support until May 12, 2026, but we should take the time to upgrade and not wait for .net 10. 

### Additional Information

[.NET Core Support lifecycle](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
[Container Patching](https://pedia.altinn.cloud/altinn-3/ops/patching/containers/#net-core)

### Tasks

- [ ] Update base images in the dockerfile for .net9
- [ ] Bump all projects; src and test, to .net9
- [ ] Update any build pipelines to support .net9
- [ ] Update any github workflows with .net9
- [ ] Check if we need to change anything in SonarCloud

### Acceptance Criterias

- [ ] Storage is built with .net9 tooling and run on .net9 Description
