### ISSUE TITLE
Automate the publishing of nuget package for Storage.Interface

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#60]
### Description

Currently, the publishing of the nuget package is manual. This should be automated.		

### Additional Information

Workflow set up for Altinn/app-lib-dotnet can be used as reference

https://github.com/Altinn/app-lib-dotnet/blob/main/.github/workflows/publish-release.yml

Configuration:
[Directory.Build.props](https://github.com/Altinn/app-lib-dotnet/blob/main/src/Directory.Build.props)

[Directory.Build.targets](https://github.com/Altinn/app-lib-dotnet/blob/main/src/Directory.Build.targets)

### Tasks

- [x] Prepare project to support automatic publishing (remove version details from .csproj)
- [x] Create workflow for automatic publising
- [x] Create new release of current v 3.17.0
- [x] Documentation (setup should be documented)
- [x] QA
- [x] Test

### Acceptance Criterias

- Publishing of Storage.Interface as a nuget package is handled in GitHub rather than manually by each developer.

**Comment by acn-sbuad** [comment]
New tag triggers action. Verification of pushing of nuget will be tested once we have relevant changes to deploy.
