### ISSUE TITLE
Replace Microsoft.Azure.KeyVault dependency with Azure.Security.KeyVault 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#77]
### Description

Storage.csproj har references to an outdated package Microsoft.Azure.KeyVault  this should be replaced by resource specific packages for certificates, keys and secrets. [Migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md)

### Tasks
- [x] Change implementation to use the new package
- [x] Test

### Acceptance Criterias

- [ ] Storage no longer references the deprecated package
- [ ] Regression tests are successful
