### ISSUE TITLE
Keep last changed on instance updated when there are changes in data elements

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#99]
### Description

The message box api currently depends on data elements to identify correct _last changed_ values. Getting all data elements for all instances in that way is a performance issue. Testing has detemined large improvements to performance for the message box API if we remove getting all data elements.

In this issue we want to test out the patching API for CosmosDB. It should be possible to surgically add/update specific properties in an instance document. 

These updates to _last changed_ values are non-critical. We can allow an update to fail or updates to happen in the wrong order. As long as the instance is kept somewhat up to date with changed in data elements. We could even consider a circuit breaker feature that stops some updates if an app is overly chatty (future feature).

### Additional Information

Microsoft documentation of the patching API:
https://learn.microsoft.com/en-us/azure/cosmos-db/partial-document-update

**One concern**: 
Is it okay that Storage have more and more logic bound to apps? What if Instance and DataElements are to be used for something else?

### Tasks

- [ ] Look for patching support in the CosmosDB library currently in use.
- [ ] Create a new Instance Service method that can update `lastChanged` and `lastChangedBy` speficially.
- [ ] Implement use of the service when data elements are added/removed/updated.
- [ ] Implement automated tests. E.g:
    - [ ] Update DataElement (e.g PUT form)
    - [ ] Download instance and check lastchanged

### Acceptance Criterias

- [ ] Instance `lastChanged` and `lastChangedBy` values are updated when a user is making changes to a data element.

**Comment by HenningNormann** [comment]
Hvis oppdatering av simple property ikke er mulig, er det vel mulig å oppdatere hele dokumentet? Og hvis det ikke er mulig å oppdatere hele dokumentet p.g.a. race conditions, så er vel dette nok et argument for å vurdere relasjonsdatabase.

**Comment by b-brodie-digdir** [comment]
Legge til et eksempel på bruken av Patch APIet via .NET klienten. 

```
            await InstanceContainer.PatchItemAsync<Instance>(dataElement.Id, partitionKey, new[]
            {
                PatchOperation.Set("/lastChanged", dataElement.LastChanged),
                PatchOperation.Set("/lastChangedBy", dataElement.LastChangedBy),
            });
```

Hvis dataElements ble lagret i samme container som instanser, kan man oppdatere begge deler i en transaksjon:

```
            PartitionKey partitionKey = new PartitionKey(dataElement.InstanceGuid);

            TransactionalBatch batch = Container.CreateTransactionalBatch(partitionKey);

            batch.PatchItem("instance_" + dataElement.InstanceGuid, new[]
            {
                PatchOperation.Set("/lastChanged", dataElement.LastChanged),
                PatchOperation.Set("/lastChangedBy", dataElement.LastChangedBy),
            });

            await batch.ExecuteAsync();

            return dataElement;
        }
```

**Comment by annerisbakk** [comment]
Må ses i sammenheng med #331

**Comment by SandGrainOne** [comment]
This is a duplicate of #331
